version: '3.8' ## CONFIG_URL=/var/www/html/config
services:
  postgres:
    image: postgres:13
    restart: always
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
    env_file:
      - ./process.env
    ports:
      - '5432:5432'
    networks:
      - developing_net
    container_name: postgres

  # pgadmin: #! Administrador de Base de datos
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  #     PGADMIN_DEFAULT_PASSWORD: "admin"
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - developing_net
  #   container_name: pgadmin
      
  web:
    tty: true
    build: ./kepler_cafe/
    # working_dir:
    # volumes:
    #   - ./:/kepler_cafe
    ports:
      - "8000:8000"
    env_file:
      - ./process.env
    depends_on:
      - postgres
    networks:
      - developing_net
    container_name: web
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn -b 0.0.0.0:8000 kepler_cafe.wsgi:application
    # command: ./manage.py runserver 0.0.0.0:8000
networks:
  developing_net: